<?php

echo "<h1>Hello!</h1>";

echo $this->tag->linkTo(["signup", "Sign Up Here!", 'class' => 'btn btn-primary']);

if ($employees->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Employees quantity: <?php echo $employees->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($employees as $employee) { ?>
            <tr>
                <td><?php echo $employee->id; ?></td>
                <td><?php echo $employee->name; ?></td>
                <td><?php echo $employee->email; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}
